### ISSUE TITLE
A few suggestions.

### ISSUE THREAD

**Issue by JourneyOver** [superbob/clicker-heroes-1.0-hsoptimizer#1]
1 - the tick spots for the play-styles are kinda funky (they are overlapping the words almost and they are off center from where they should technically be at). I'd say put them in a way like below instead of going left to right or at least moving the circles over to the right just a slight bit.
- Idle
- Hybrid
- Active

2 - Have the delta spots be clickable which would change the numbers to a format that you can input into the "v" custom numbers thing for ancients. (they can't have "," or "." in them to make them compatible)

3 - if you are going to have scientific notation for your numbers make them like "1.123e6" instead of "1.123420e6" though I would prefer to have an option to have either scientific notation or just a normal number mode.

4 - maybe have an option to switch the ratios between 0.1 or 0.5 or have an option to let us input our own ratio.

5 - Would like to see the ability ancients for active/hybrid included if possible. could have them mapped out so they are equal to bubos or chronos since that's usually how people have them set out to be anyways.

**Comment by superbob** [comment]
Thanks for the feedback.
1. This is strange as it didn't strike me while in development mode, now I see it. I'll fix it soon™.
2. This is a good idea, I'll try to implement it soon also. I consider adding a small button next to each delta to copy directly to the clipboard when the number is clicker using https://clipboardjs.com/ ?
3. I choose to turn automatically into exponential notation when > 100 000, I'd like to stick with this but it can change if needed. The precision was as large as possible (to be the most exact possible). However, I'm okay to reduce precision and have less decimals to improve readability.
4. I'll try to implement it but it's not on my top priority list.
5. There are no rules for them, I usually upgrade them depending on remaining HS that I have left after leveling everyone else, however, I could add an option.

**Comment by superbob** [comment]
Closing the issue as tickets have been created for each suggestion/issue.
Please comment in specific item if needed.
