### ISSUE TITLE
Calc hangs on my save

### ISSUE THREAD

**Issue by kirilye** [superbob/clicker-heroes-1.0-hsoptimizer#10]
Here is my save. 
Script hangs on it:

[removed-link](https://nowhere.com/)

**Comment by superbob** [comment]
I've downloaded the save, thanks,

I remove the link as it contain some personal data (email). I've not checked, but it may also contain clan data (id) which should not be available publicly also.

**Comment by superbob** [comment]
I'm not 100% sure, but I think it's related to #8

**Comment by superbob** [comment]
It's linked to #8. I'm implementing a fix for it that fixes this issue

**Comment by kirilye** [comment]
Thanks!
