### ISSUE TITLE
Issue with ancients price calculation

### ISSUE THREAD

**Issue by Narzaal** [superbob/clicker-heroes-1.0-hsoptimizer#13]
The calculator tell me to do this :

> You have 392 HS in stock
> 
> Ancient   Current Goal    Delta
> Atman 6   7   +1
> Dogcog    2   2   +0
> Dora  5   6   +1
> Fortuna   3   4   +1
> Kumawakamaru  1   2   +1
> Libertas  22  28  +6
> Mammon    22  28  +6
> Mimzee    22  28  +6
> Siyalatas 24  30  +6

But when I try to do this, I finish with Siyalatas at 29 with 5 HS left and I need 14 HS to go to 30.

I think it's because of Chor'gorloth who give me -53,67% ancient cost.

**Comment by superbob** [comment]
Chor should be taken care of.

I need to have some more information:
- What's your level of Chor and Phandoryss? (I guess Chor is 15, but I can't guess Phan)
- What's your ascend level ?
- What's your total number of AS (ever earn)?
- What's your playstyle? (Idle I guess) If hybrid, what ratio?

**Comment by superbob** [comment]
If I take arbitrary values for Phandoryss (3), ascend level (200), total AS (60). I get the same recommendations than those you have reported and the calculator computes an expected cost of 390 HS which is just below your HS in stock so you should be able to afford to buy them!

How did you bought levels? This calculator supposes you enter the level number in the 'v' box. (Click the "LVL UP" button while pressing 'V' on the keyboard, then enter the number and press enter).

If you buy levels separately (click many times on the "LVL UP" button to buy single levels). Rounding can be unfavorable to you and you could have lost some HS (at least 3 in your case) in the process.
That could be an explanation.

**Comment by Narzaal** [comment]
Ok I didn't know this v method ! It's probably that. I can't verify the value because I forgot my laptop yesterday in the train ... my fault ... but thanks for the information !

**Comment by superbob** [comment]
Oh, I'm sorry for your laptop... I'm closing this issue. Don't hesitate to reopen it if you observe this even using the 'v' box.
