### ISSUE TITLE
kuma

### ISSUE THREAD

**Issue by iceltd** [superbob/clicker-heroes-1.0-hsoptimizer#16]
hello, i have checked some calculators and noticed that your kuma is much lower compared to other calcs.
maybe you have a math problem.
can you check the formula pls
2.844·ln(siya) - 1.422·ln(alpha) - 1.422·ln(0.25 + e-0.01·oldKuma ) - 7.014

thank you

**Comment by superbob** [comment]
You are right, the formula I use currently is:

```
2.88 * ln(siya) - 1.44 * ln(alpha) - 1.44 * ln(0.25 + exp(-0.001 * oldKuma)) - 10.42
```

(You can find it at [formulas.service.js#L44-L46](https://github.com/superbob/clicker-heroes-1.0-hsoptimizer/blob/335f13b7304627065a4e515edeb3fb3c4e08f8ad/src/app/components/formulas/formulas.service.js#L44-L46))
All the parameters are wrong :disappointed:

[Math and Transcendance](https://www.reddit.com/r/ClickerHeroes/comments/4naohc/math_and_transcendance), which I'm based on, confirm your formula also.

I don't know how I came to it (I didn't invent it from nowhere :confused:). Did it change sometime?

Anyway, thanks for reporting, I'll fix it!
