### ISSUE TITLE
Clipboard number format is incorrect for large numbers

### ISSUE THREAD

**Issue by yukidaruma** [superbob/clicker-heroes-1.0-hsoptimizer#23]
![chrome_2016-12-24_17-19-06](https://cloud.githubusercontent.com/assets/6897821/21466035/21fa6934-c9fd-11e6-9c34-b3224754a0c5.png)

If I paste this, it spends as many souls as possible (so I have to manually type it).

Can you fix this?

**Comment by ljaszcza** [comment]
I second this, the paste is wrong at large numbers.

**Comment by superbob** [comment]
I'm currently on vacation so I can't fix the bug now. I'll dig into it later.

**Comment by superbob** [comment]
The fix should make it work until ~e50. There may be a problem after that ...

**Comment by yukidaruma** [comment]
Thanks 😄
