### ISSUE TITLE
Wrong values. I'm at 10k plus Moeru

### ISSUE THREAD

**Issue by althras** [superbob/clicker-heroes-1.0-hsoptimizer#24]
The calculator is copying values like this to the clipboard. I'm not sure if it's a valid number format?
5.0091790451207075e+63e30

![Example Image](https://cloud.githubusercontent.com/assets/3817939/22627826/50dd3a78-ec04-11e6-8f54-98bcb4fab29c.png)

The reason why Argaiv, Bhaal and Fragsworth are uneven is due to copy and pasting from the calculator. Same reason Mammon and Mimzee is uneven. The values are way more than hero souls affordable.

**Comment by superbob** [comment]
It's an error that seem to be linked to #23, I'm gonna investigating on it

**Comment by superbob** [comment]
I couldn't check my fix with a real save file, only with "fake" sample data. Feel free to re-open the issue in case the fix doesn't work well.
