### ISSUE TITLE
Provide an easy way to copy delta levels to an appropriate output format

### ISSUE THREAD

**Issue by superbob** [superbob/clicker-heroes-1.0-hsoptimizer#3]
Provide a way to easily copy the _delta_ level of a given ancient.

The format of the copied level should be compatible with the input format in the game when pressing "v" and entering the given amount of levels to upgrade to.

The format is numerical with an optional exponent specified (e.g: 15000, 15e7). No comma or dot is allowed (e.g: ~~1.5~~, ~~1,5~~, ~~1.47e7~~).

See #1 (2) for the original report of the feature.

**Comment by superbob** [comment]
Look into https://clipboardjs.com/ to automatically copy into the clipboard without pressing _Ctrl+C_

**Comment by JourneyOver** [comment]
I don't think scientific numbers work for the input format in the game either, believe it's just plain numbers (e.g: 15000) that work for the input format.

**Comment by superbob** [comment]
In fact exponential notation without dots or comma works! (e.g: 15e6, ~~not 1.5e7~~). I already tested in the game for levels of Morgulis :smile:.
I believe (not 100% sure) that suffixes don't work (15K, 12M). So it's either plain (that could be looong) either exponential without comma/dots.

The "value" input box supports numbers (0-9) and 'e' character.

**Comment by JourneyOver** [comment]
Ah okay cool didn't know that as most calculators that I've seen and used myself have used just normal plain numbers when it comes to that part and I'm not home so I couldn't really test it out to see if it worked that way or not but good to know :D
