### ISSUE TITLE
Option to enable/disable scientific numbers

### ISSUE THREAD

**Issue by superbob** [superbob/clicker-heroes-1.0-hsoptimizer#5]
Have an option to have either scientific notation or just a normal number mode.

See #1 (3) for the original report of the feature.

**Comment by superbob** [comment]
Should _normal_ mode consider game suffixes (K, M, B, ...) ? Or plain numbers (that could go to 100000000000000000...).

**Comment by JourneyOver** [comment]
Depending on how you do #3 either through how like the kepow calculator does it or have a button on the side or something that'll copy the number it could go either way.

Kepows method -- have the delta numbers in a box and they either are in scientific notation or are in the game suffix mode depending on the option that is chosen (though if this way is taken you don't really need to worry to much about all this and just have it in scientific notation for the first part) but upon clicking the box the number changes to plain numbers (and the numbers are just in the box so they are not spilling over to other areas when the numbers start getting big) to make it easy to copy for the custom numbers for ancients thing.

Other method -- If you go the route of having a button to the side of the numbers that will copy the delta for said ancient for you automatically or something then I'd say go by game suffix mode instead as plain numbers would start to be way to big at some point.

**Comment by superbob** [comment]
Maybe the best could be to follow how the game actually works:

Default: use notation with suffixes (K, M, B, ...). And when arrived at a certain point (no more suffixes), switch to scientific notation => I think it'll be hard to reach that point because the greatest suffix correspond to a really big amount of HS :smile:.

With the "_scientific_" option: use plain number up to 100 000, then switch to scientific notation directly (the current behavior).

**Comment by JourneyOver** [comment]
Hmm yea either of those two options could work as well :p do like the sound of the first option though I haven't actually seen any calculators do it that way yet, as most go the second option but have plain numbers go up to 1 000 000 before switching over to scientific notation.

**Comment by superbob** [comment]
There is an option in the game to switch between scientific or normal number display, I could read this option in the save file to set a default value.

**Comment by JourneyOver** [comment]
Hmm yea that could work as well, any option is fine to be honest. I think as long as #4 gets implemented anything will work because the scientific notations will be a lot shorter anyways compared to how they are now.
