### ISSUE TITLE
Page hangs/crashes when getting into big numbers area

### ISSUE THREAD

**Issue by JourneyOver** [superbob/clicker-heroes-1.0-hsoptimizer#8]
I haven't personally experienced this yet but I'm sure it'll hit me eventually since I'm starting to get into bigger and bigger numbers but I've seen several reports now in the thread on reddit for your calculator which calls that it's not just a specific problem for one person. 

What seems to be happening is upon pasting in the save and it trying to load said save it seems to end up just hanging or crashing the page/script until you kill the script. Only one person has put up a decoded save though you'll probably actually want the save file instead to do some testing.

> Outsiders: Xyliqil (3), Chor'gorloth (10), Phandoryss (11), Borb (13), Ponyboy (19);
> Ancients: Morgulis (92,100,000,000,000,030,000), Argaiv (9,560,010,001), Siyalatas (9,560,010,000), Mammon (8,840,000,001), Mimzee (8,840,000,001), Libertas (8,840,000,000), Bhaal (3,000,000,001), Fragsworth (3,000,000,001), Solomon (200,030,000), Juggernaut (20,000,001), Atman (62), Kumawakamaru (62), Sniperino (60), Dora (59), Vaagur (59), Dogcog (58), Fortuna (58), Revolc (57), Bubos (56), Chawedo (55), Hecatoncheir (55), Berserker (55), Kleptos (55), Energon (55), Chronos (53);
> 
> Not Summoned: Pluto;
> 
> Gilded Heroes: Wepwawet (638);
> 
> Misc: TP (2.09%); HS (7.723,783,488,388,558e+21; Spent on Ancients/Rerolls: 336,375,661,249,554,150,000/3,318; Total: 8.060,159,149,638,112e+21) HZE: 6,473; Current Zone: 3; Ascensions: 3,246; Immortal Damage: 2.6,045,375,314,333,438e+22; Rubies: 356; Forge Cores: 30,466; Total Relics Found: 3,304; Achievements: 86%;
> 
> Time: Since Start: 630 days; Since Transcension: 3 days; Since Ascension: 0h 13m;
> 
> Total Relic Bonuses:
> +4.42 Atman
> +17.17 Kumawakamaru
> +91.00 Energon
> +170.00 Sniperino

**Comment by superbob** [comment]
Yep, I had that in mind.

I'd like to have a sample savegame (either raw encoded or decoded JSON) with such great numbers because I'm not sure how they are represented.

I have ideas to handle that, but it'll not be easy to implement ...

**Comment by JourneyOver** [comment]
Alright I shot a message to someone who posted about the issue asking them to get their save over here so hopefully you'll have one soon enough to be able to do some testing to see what is causing this issue.

**Comment by JourneyOver** [comment]
Here is a random save edit that I made that makes the script crash, tested it on other calculators and it works on others so I know that the save is at least working.

http://pastebin.com/kTzfCcf7

**Comment by superbob** [comment]
Good.

Be carfeul, the savedata should be exchanged by PM or email because it contain some sensitive data when member of a clan.

**Comment by JourneyOver** [comment]
it's an old save (that I just edited in some huge numbers) that I have long since abandoned in a test clan by myself that I created so nothing sensitive can be thrown around.

**Comment by JourneyOver** [comment]
here is another save, this one is from wyand (he doesn't have a github account so I had him send me the save).

http://pastebin.com/RG2S8iYc

(he edited out his clan info before hand)

**Comment by superbob** [comment]
I'm implementing a fix for this issue (and #10 that is a duplicate). It works with all save files provided.
